<#
.SYNOPSIS
    Generates ext_init.c and (optionally) ext_embed_rules.mak from a list of
    embedded SQLite extension source files.
.PARAMETER ExtensionFiles
    Space-separated list of .c filenames (e.g. "csv.c eval.c series.c").
    Pass an empty string to generate a no-op register_embedded_extensions().
.PARAMETER OutputFile
    Path to write the generated .c file (typically ext_init.c).
.PARAMETER RulesFile
    Optional. Path to write the generated NMAKE rules file
    (typically ext_embed_rules.mak). When provided, one explicit compile rule
    per extension is written so NMAKE knows how to build *_emb.obj files.
#>
param(
    [string]$ExtensionFiles = "",
    [string]$DepFiles = "",
    [string]$OutputFile = "ext_init.c",
    [string]$RulesFile = ""
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Get-InitFuncName([string]$filename) {
    # Try to discover the actual init function from the source file
    if (Test-Path $filename) {
        $content = Get-Content $filename -Raw
        if ($content -match '(?m)^\s*int\s+(sqlite3_\w+_init)\s*\(') {
            return $Matches[1]
        }
    }
    # Fall back to deriving the name from the filename
    $base = [System.IO.Path]::GetFileNameWithoutExtension($filename)
    $base = $base.Replace("-", "_")
    return "sqlite3_${base}_init"
}

$files = [string[]]@()
if ($ExtensionFiles.Trim() -ne "") {
    $files = [string[]]($ExtensionFiles.Trim() -split '\s+' | Where-Object { $_ -ne "" })
}

$depList = [string[]]@()
if ($DepFiles.Trim() -ne "") {
    $depList = [string[]]($DepFiles.Trim() -split '\s+' | Where-Object { $_ -ne "" })
}

# ── Generate ext_init.c ──────────────────────────────────────────────────────

$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add("/* Auto-generated by gen_embed_init.ps1 -- do not edit */")

if ($files.Count -gt 0) {
    $lines.Add('#include "sqlite3.h"')
    $lines.Add("")
    foreach ($f in $files) {
        $fn = Get-InitFuncName $f
        $lines.Add("extern int ${fn}(sqlite3 *, char **, const sqlite3_api_routines *);")
    }
    $lines.Add("")
    $lines.Add("void register_embedded_extensions(void) {")
    $lines.Add("    int rc;")
    foreach ($f in $files) {
        $fn = Get-InitFuncName $f
        $lines.Add("    rc = sqlite3_auto_extension((void(*)(void))${fn});")
        $lines.Add("    if (rc != SQLITE_OK) {")
        $lines.Add("        /* extension registration failed; sqlite3_open() will surface the error */")
        $lines.Add("    }")
    }
    $lines.Add("}")
} else {
    $lines.Add("")
    $lines.Add("void register_embedded_extensions(void) {")
    $lines.Add("}")
}

$content = $lines -join "`n"
[System.IO.File]::WriteAllText($OutputFile, $content + "`n")
[int]$nExt = $files.Count
[int]$nDep = $depList.Count
Write-Host "gen_embed_init.ps1: wrote $nExt extension(s), $nDep dep(s) to $OutputFile"

# ── Generate ext_embed_rules.mak (optional) ──────────────────────────────────

if ($RulesFile -ne "") {
    $rlines = [System.Collections.Generic.List[string]]::new()
    $rlines.Add("# Auto-generated by gen_embed_init.ps1 -- do not edit")
    $rlines.Add("# Compile rules for embedded extension objects (*_emb.obj).")
    $rlines.Add("# Each rule uses CFLAGS_EMBEDDED (-DSQLITE_CORE) so SQLITE_EXTENSION_INIT")
    $rlines.Add("# macros expand to no-ops and the extension calls SQLite directly.")
    $rlines.Add("# After changing EMBED_EXTENSIONS, run: nmake setup-embed")
    $rlines.Add("")

    foreach ($f in $files) {
        $base = [System.IO.Path]::GetFileNameWithoutExtension($f)
        $obj  = "${base}_emb.obj"
        # TAB character required for NMAKE recipe lines
        $tab  = "`t"
        $rlines.Add("${obj}: ${f}")
        $rlines.Add("${tab}`$(CC) `$(CFLAGS_EMBEDDED) /c ${f} /Fo${obj}")
        $rlines.Add("")
    }

    if ($depList.Count -gt 0) {
        $rlines.Add("# Companion dependency objects (_dep.obj) -- no init function, symbols only")
        $rlines.Add("")
        foreach ($f in $depList) {
            $base = [System.IO.Path]::GetFileNameWithoutExtension($f)
            $obj  = "${base}_dep.obj"
            $tab  = "`t"
            $rlines.Add("${obj}: ${f}")
            $rlines.Add("${tab}`$(CC) `$(CFLAGS_EMBEDDED) /c ${f} /Fo${obj}")
            $rlines.Add("")
        }
    }

    $rcontent = $rlines -join "`n"
    [System.IO.File]::WriteAllText($RulesFile, $rcontent + "`n")
    Write-Host "gen_embed_init.ps1: wrote $nExt extension(s) and $nDep dep(s) to $RulesFile"
}

exit 0
