name: CI
on:
  push:
    branches: [ master, main, develop, release/*, hotfix/* ]
  pull_request:
    branches: [ master, main, develop, release/*, hotfix/* ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  run-selected-unittests:
    runs-on: windows-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    name: Run MSBuild and VSTest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        id: checkout_code
        with:
          path: sqliteodbc
      
      - name: Checkout sqllogictest
        uses: actions/checkout@v4
        with:
          repository: msi-cxb/sqllogictest
          path: sqllogictest

      - name: get directory listing
        id: get_directory_listing
        shell: cmd
        run: |
          dir /b /s
  
      - name: Setup MSBuild and add to PATH
        uses: microsoft/setup-msbuild@v2
        id: setup_msbuild
        with:
          msbuild-architecture: x64

      - name: config shell for VS2022
        id: config_vs2022
        shell: cmd
        run: |
          SET __DEBUGECHO=ECHO
          IF NOT DEFINED __DEBUGECHO (SET __DEBUGECHO=REM)
          
          SET VSVARS32=%VSWHEREINSTALLDIR%\Common7\Tools\VsDevCmd.bat
          IF EXIST "%VSVARS32%" (
                  set CLARG=-arch=amd64
                  VSVARS32="%VSVARS32%" %CLARG%
                  %__DEBUGECHO% VSVARS32="%VSVARS32%" %CLARG%
          )
          SET VSVARS32=%VSVARS32:\\=\%
          %__DEBUGECHO% "%VSVARS32%" %CLARG%
          CALL "%VSVARS32%" %CLARG% 1>nul

          IF DEFINED VSWHERE_EXE GOTO skip_setVsWhereExe
          SET VSWHERE_EXE=%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe
          IF NOT EXIST "%VSWHERE_EXE%" SET VSWHERE_EXE=%ProgramFiles%\Microsoft Visual Studio\Installer\vswhere.exe
          :skip_setVsWhereExe
      
          IF NOT EXIST "%VSWHERE_EXE%" (
              ECHO The "VsWhere" tool does not appear to be installed.
              GOTO :EOF
          ) ELSE (
              %__DEBUGECHO% VSWHERE_EXE="%VSWHERE_EXE%"
          )
          SET VS_WHEREIS_CMD="%VSWHERE_EXE%" -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath -latest
          %__DEBUGECHO% VS_WHEREIS_CMD=%VS_WHEREIS_CMD%
      
          FOR /F "delims=" %%D IN ('%VS_WHEREIS_CMD%') DO (SET VSWHEREINSTALLDIR=%%D)
      
          IF NOT DEFINED VSWHEREINSTALLDIR (
              ECHO Visual Studio 2017 / 2019 / 2022 is not installed.
          GOTO :EOF
          )
          %__DEBUGECHO% Visual Studio 2017 / 2019 / 2022 is installed.
          %__DEBUGECHO% VsWhereInstallDir = '%VSWHEREINSTALLDIR%'
      







      - name: Run script to build ODBC driver
        id: run_vs2022
        shell: cmd
        run: |
          cd sqliteodbc
          buildAndInstall.bat 64 true

      - name: Build sqllogictest
        id: build_sqllogictest
        shell: cmd
        run: |
          cd sqllogictest/src
          nmake -f Makefile.msc

      - name: Run sqllogictest
        id: run_sqllogictest
        shell: cmd
        run: |
          cd sqllogictest/src
          run-all-odbc.bat
    
      - name: Run test script
        id: run_testscript
        shell: cmd
        run: |
          cd sqliteodbc
          run_sqliteODBC_test_WSF.bat 64
