name: CI
on:
  push:
    branches: [ master, main, develop, release/*, hotfix/* ]
  pull_request:
    branches: [ master, main, develop, release/*, hotfix/* ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  run-selected-unittests:
    runs-on: windows-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    name: Run MSBuild and VSTest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        id: checkout_code
      
      - name: Checkout sqllogictest
        uses: actions/checkout@v4
        with:
          repository: msi-cxb/sqllogictest
          path: sqllogictest

      - name: get directory listing
        id: get_directory_listing
        shell: cmd
        run: |
          dir /b /s
  
      - name: Setup MSBuild and add to PATH
        uses: microsoft/setup-msbuild@v2
        id: setup_msbuild
              
      - name: Run MSBuild
        id: run_msbuild
        shell: cmd
        run: |
          buildAndInstall.bat 64 true

      - name: Run test script
        id: run_testscript
        shell: cmd
        run: |
          run_sqliteODBC_test_WSF.bat 64

            
      # - name: install ODBC
      #   id: install_odbc
      #   shell: cmd
      #   run: |
      #     cd sqliteODBC64
      #     .\SQLiteODBCInstaller.exe -q -i -d=sql3
      
      # - name: Run the executable
      #   id: run_executable
      #   shell: powershell
      #   run: |
      #     .\bin\Debug\net8.0\csharp_DotNet8_ODBC.exe
      #     exit $LASTEXITCODE
