name: CI
on:
  push:
    branches: [ master, main, develop, release/*, hotfix/* ]
  pull_request:
    branches: [ master, main, develop, release/*, hotfix/* ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  run-selected-unittests:
    runs-on: windows-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    name: Run MSBuild and VSTest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        id: checkout_code
        with:
          path: sqliteodbc
      
      - name: Checkout sqllogictest
        uses: actions/checkout@v4
        with:
          repository: msi-cxb/sqllogictest
          path: sqllogictest

      - name: get directory listing
        id: get_directory_listing
        shell: cmd
        run: |
          dir /b /s
  
      - name: Setup MSBuild and add to PATH
        uses: microsoft/setup-msbuild@v2
        id: setup_msbuild
        with:
          msbuild-architecture: x64
      
      - name: Build sqllogictest
        id: build_sqllogictest
        shell: cmd
        run: |
          cd sqllogictest/src
          buildWithVisualStudio.bat

      - name: Run script to build ODBC driver
        id: run_vs2022
        shell: cmd
        run: |
          cd sqliteodbc
          buildAndInstall.bat 64 true

      - name: Run sqllogictest
        id: run_sqllogictest
        shell: cmd
        run: |
          cd sqllogictest/src
          run-all-odbc.bat
    
      - name: Run test script
        id: run_testscript
        shell: cmd
        run: |
          cd sqliteodbc
          run_sqliteODBC_test_WSF.bat 64
