name: CI
on:
  push:
    branches: [ master, main, develop, release/*, hotfix/* ]
  pull_request:
    branches: [ master, main, develop, release/*, hotfix/* ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  run-selected-unittests:
    runs-on: windows-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    name: Run MSBuild and VSTest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        id: checkout_code
        with:
          path: sqliteodbc
      
      - name: Checkout sqllogictest
        uses: actions/checkout@v4
        with:
          repository: msi-cxb/sqllogictest
          path: sqllogictest

      - name: Setup MSBuild and add to PATH
        uses: microsoft/setup-msbuild@v2
        id: setup_msbuild
      
      - name: build 32 bit ODBC driver
        id: build_32_bit_ODBC_driver
        shell: cmd
        run: |
          cd sqliteodbc
          buildAndInstall.bat 32 true

      - name: build 64 bit ODBC driver
        id: build_64_bit_ODBC_driver
        shell: cmd
        run: |
          cd sqliteodbc
          buildAndInstall.bat 64 true

      - name: build 32 bit sqllogictest
        id: build_32_bit_sqllogictest
        shell: cmd
        run: |
          cd sqllogictest/src
          buildWithVisualStudio.bat 32

      - name: build 64 bit sqllogictest
        id: build_64_bit_sqllogictest
        shell: cmd
        run: |
          cd sqllogictest/src
          buildWithVisualStudio.bat 64

      - name: test for 32/64 bit sqllogictest and sqliteodbc for this shell
        id: test_sqllogictest
        shell: cmd
        run: |
          cd sqllogictest/src
          where sqllogictest_32.exe
          c:\windows\syswow64\cscript //Nologo getInstalledODBCDrivers.vbs
          sqllogictest_32 --odbc "DSN=SQLite3 Datasource;DATABASE=:memory:;" --verify ..\test\select1.test
          where sqllogictest_64.exe
          c:\windows\system32\cscript //Nologo getInstalledODBCDrivers.vbs
          sqllogictest_64 --odbc "DSN=SQLite3 Datasource;DATABASE=:memory:;" --verify ..\test\select1.test

      - name: run full 32 bit sqllogictest
        id: run_full_32_bit_sqllogictest
        shell: cmd
        run: |
          cd sqllogictest/src
          run-all-odbc.bat 32
    
      - name: run full 64 bit sqllogictest
        id: run_full_64_bit_sqllogictest
        shell: cmd
        run: |
          cd sqllogictest/src
          run-all-odbc.bat 64
    
      - name: run 32 bit testscript
        id: run_32_bit_testscript
        shell: cmd
        run: |
          cd sqliteodbc
          run_sqliteODBC_test_WSF.bat 32

      - name: run 64 bit testscript
        id: run_64_bit_testscript
        shell: cmd
        run: |
          cd sqliteodbc
          run_sqliteODBC_test_WSF.bat 64
