name: CI
on:
  push:
    branches: [ master, main, develop, release/*, hotfix/* ]
  pull_request:
    branches: [ master, main, develop, release/*, hotfix/* ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  run-selected-unittests:
    runs-on: windows-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    name: Run MSBuild and VSTest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        id: checkout_code
        with:
          path: sqliteodbc
      
      - name: Checkout sqllogictest
        uses: actions/checkout@v4
        with:
          repository: msi-cxb/sqllogictest
          path: sqllogictest

      - name: Setup MSBuild and add to PATH
        uses: microsoft/setup-msbuild@v2
        id: setup_msbuild
        with:
          msbuild-architecture: x64
      
      - name: Run script to build 32 and 64 bit ODBC driver
        id: run_vs2022
        shell: cmd
        run: |
          cd sqliteodbc
          buildAndInstall.bat 32 true
          buildAndInstall.bat 64 true

      - name: Build sqllogictest
        id: build_sqllogictest
        shell: cmd
        run: |
          cd sqllogictest/src
          cscript //Nologo getInstalledODBCDrivers.vbs
          buildWithVisualStudio.bat 32
          buildWithVisualStudio.bat 64

      - name: test for 32/64 bit sqllogictest and sqliteodbc for this shell
        id: test_sqllogictest
        shell: cmd
        run: |
          cd sqllogictest/src
          REM 32 bit
          where sqllogictest_32.exe
          c:\windows\syswow64\cscript //Nologo getInstalledODBCDrivers.vbs
          sqllogictest_32 --odbc "DSN=SQLite3 Datasource;DATABASE=:memory:;" --verify ..\test\select1.test
          REM 64 bit
          where sqllogictest_64.exe
          c:\windows\system32\cscript //Nologo getInstalledODBCDrivers.vbs
          sqllogictest_64 --odbc "DSN=SQLite3 Datasource;DATABASE=:memory:;" --verify ..\test\select1.test

      - name: Run full sqllogictest
        id: run_sqllogictest
        shell: cmd
        run: |
          cd sqllogictest/src
          run-all-odbc.bat 32
          run-all-odbc.bat 64
    
      - name: Run test script
        id: run_testscript
        shell: cmd
        run: |
          cd sqliteodbc
          run_sqliteODBC_test_WSF.bat 32
          run_sqliteODBC_test_WSF.bat 64
