name: virustotal

on:
  release:
    types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  virustotal:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        id: checkout_code
        uses: actions/checkout@v4

      - name: VirusTotal Scan
        uses: crazy-max/ghaction-virustotal@v4
        with:
          vt_api_key: ${{ secrets.VT_API_KEY }}
          update_release_body: true
          files: |
            *.exe
            *.dll
            *.patch

