name: virustotal

on:
  workflow_dispatch:
  
  release:
    types: [published]

#  workflow_run:
#    workflows: [release]
#    types:
#      - completed

jobs:
  virustotal:
    name: 'virustotal'
    environment: virustotal
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - name: 'VirusTotal Scan'
        uses: cssnr/virustotal-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          vt_api_key: ${{ secrets.VT_API_KEY }}
          rate_limit: 4
          update_release: true

